### ISSUE TITLE
Problem with recent esp-idf

### ISSUE THREAD

**Issue by newaddressunknown** [Lucas-Bruder/ESP32_LED_STRIP#19]
I was not fortunate enough to get the leds to work with the current esp-idf (commit #cca8834). I wonder if you have a similar experience.

**Comment by mattheweshleman** [comment]
I just filed a case that helps explain this:
https://github.com/espressif/esp-idf/issues/187

After I changed led_strip.c code from:

``esp_err_t install_ok = rmt_driver_install(rmt_cfg.channel, 0, led_strip->rmt_interrupt_num);
``
to
`esp_err_t install_ok = rmt_driver_install(rmt_cfg.channel, 0, 0);
`

the issue is fixed (note the 3rd param). See my working LED strip picture here (and references to other people that helped me find this solution):

https://twitter.com/EshlemanMatthew/status/814664422111268865

**Comment by mattheweshleman** [comment]
pull request now available if that helps:
https://github.com/Lucas-Bruder/ESP32_LED_STRIP/pull/20

**Comment by Lucas-Bruder** [comment]
#20 merged
